spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: gerson
    password: gerson
    driverClassName: com.mysql.cj.jdbc.Driver